Popup window
Swarzstein/Portfolio pull request #10
Opened 2022-09-16 14:12 UTC by Swarzstein

2022-09-17 21:47 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @sonyco-4u 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️

- Kindly make sure you implement properly the functionality of the pop-up window as it require in the project I list more detail below kindly check them :+1: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-17 21:47 UTC, MaganaAsiati commented on js/main.js
> +  document.querySelector('#card-modal').classList.toggle('hidden');
- Hey :hand: Here you did a great job here but make sure your project working properly as explained below when we clique to the see project button shown below  the popup appear with the detail of the project :+1: :smiley: 


![image](https://user-images.githubusercontent.com/95297251/190876467-539a8a75-bb60-4cb3-b54d-e22af2ab886b.png)

The [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters is set correctly project repository.
When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
When the user clicks (or taps) the close (X) button, the popup disappears.
The popup is responsive, it fits mobile and desktop sizes properly.
The pop-up follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, text, margins).

2022-09-17 21:47 UTC, MaganaAsiati commented on js/main.js
> +};
- Kindly make sure you implement those points below to add the detail of each project in the pop-up :+1: 
   - The JavaScript code implements an array of objects to store JavaScript objects containing the information for each project.
   - Each object contains at least the following information about the project: name, description, featured image, technologies, link to live version, and link to the project source code. Ie: :+1: :smiley: 


```
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
```

2022-09-17 21:47 UTC, MaganaAsiati commented on index.html
> -          <button class="link-btn-2 fill-h">See Project</button>
- Kindly make sure each project has the `see project `button in your desktop version only one project have the seen button please fix that so   when someone will click on that see project button it  will show the popup with all detail of your project :+1: 

![image](https://user-images.githubusercontent.com/95297251/190877313-f369979b-2782-4d77-ba70-55b562744640.png)

2022-09-18 03:24 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @Swarzstein 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-19 16:32 UTC, merged